### ISSUE TITLE
Google login not working

### ISSUE THREAD

**Issue by Kristiyan96** [Panshak/arcinvoice#7]
Hello @Panshak 

Seems like Google Auth is not working. The user is being redirected to the Google login screen, selects an email, the Auth tab closes but `googleSuccess` in /components/Login/Login is not being called.

I forked your project and started working on [Bulkit](https://github.com/Kristiyan96/bulkit/tree/develop). Thanks for the great setup!

**Comment by Panshak** [comment]
The problem is likely from your Google auth configuration.
Please make sure that it looks like this (screenshots) but with your own domain.
![Authorized JS Origins](https://i.postimg.cc/phsVs4Lv/authorized-origin.png) 
![Authorized redirect uris](https://i.postimg.cc/MfX6N5nQ/authorize-uris.png)

**Comment by Kristiyan96** [comment]
I meant Auth is not working for www.arcinvoice.com on Brave.
I now tried with Safari and it worked
